const SUPABASE_URL = "https://oxnrxhkiaqsewgjxgtkg.supabase.co"

const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94bnJ4aGtpYXFzZXdnanhndGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzE1Nzc5NTEsImV4cCI6MTk4NzE1Mzk1MX0.v6lIDHvru-PYXuRKDgpxtZQkdQdqIEVm7TlaPfI3rrM"


const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);